//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mictlanix.DiverzaClient
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class Error : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("Error", "http://www.buzonfiscal.com/TimbradoCFDI/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.buzonfiscal.com/TimbradoCFDI/", ConfigurationName="Mictlanix.DiverzaClient.TimbradoCFDI")]
    public interface TimbradoCFDI
    {
        
        // CODEGEN: Generating message contract since the operation timbradoCFD is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.buzonfiscal.com/TimbradoCFDI/TimbradoCFDI/timbradoCFDRequest", ReplyAction="http://www.buzonfiscal.com/TimbradoCFDI/TimbradoCFDI/timbradoCFDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Mictlanix.DiverzaClient.Error), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="Error")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Mictlanix.DiverzaClient.timbradoCFDResponse timbradoCFD(Mictlanix.DiverzaClient.timbradoCFDRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/TimbradoCFD")]
    public partial class RequestTimbradoCFDType
    {
        
        private DocumentoType documentoField;
        
        private InfoBasicaType infoBasicaField;
        
        private InfoAdicionalType[] infoAdicionalField;
        
        private string refIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI", Order=0)]
        public DocumentoType Documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI", Order=1)]
        public InfoBasicaType InfoBasica
        {
            get
            {
                return this.infoBasicaField;
            }
            set
            {
                this.infoBasicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InfoAdicional", Order=2)]
        public InfoAdicionalType[] InfoAdicional
        {
            get
            {
                return this.infoAdicionalField;
            }
            set
            {
                this.infoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")]
        public string RefID
        {
            get
            {
                return this.refIDField;
            }
            set
            {
                this.refIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")]
    public partial class DocumentoType
    {
        
        private byte[] archivoField;
        
        private string nombreArchivoField;
        
        private DocumentoTypeTipo tipoField;
        
        private string versionField;
        
        public DocumentoType()
        {
            this.versionField = "3.2";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="base64Binary")]
        public byte[] Archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NombreArchivo
        {
            get
            {
                return this.nombreArchivoField;
            }
            set
            {
                this.nombreArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DocumentoTypeTipo Tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")]
    public enum DocumentoTypeTipo
    {
        
        /// <remarks/>
        ZIP,
        
        /// <remarks/>
        XML,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")]
    public partial class InfoAdicionalType
    {
        
        private string atributoField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Atributo
        {
            get
            {
                return this.atributoField;
            }
            set
            {
                this.atributoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/RequestTimbraCFDI")]
    public partial class InfoBasicaType
    {
        
        private string rfcEmisorField;
        
        private string rfcReceptorField;
        
        private string serieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RfcEmisor
        {
            get
            {
                return this.rfcEmisorField;
            }
            set
            {
                this.rfcEmisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RfcReceptor
        {
            get
            {
                return this.rfcReceptorField;
            }
            set
            {
                this.rfcReceptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Serie
        {
            get
            {
                return this.serieField;
            }
            set
            {
                this.serieField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timbradoCFDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.buzonfiscal.com/ns/xsd/bf/TimbradoCFD", Order=0)]
        public Mictlanix.DiverzaClient.RequestTimbradoCFDType RequestTimbradoCFD;
        
        public timbradoCFDRequest()
        {
        }
        
        public timbradoCFDRequest(Mictlanix.DiverzaClient.RequestTimbradoCFDType RequestTimbradoCFD)
        {
            this.RequestTimbradoCFD = RequestTimbradoCFD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class timbradoCFDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sat.gob.mx/TimbreFiscalDigital", Order=0)]
        public Mictlanix.CFDv32.TimbreFiscalDigital TimbreFiscalDigital;
        
        public timbradoCFDResponse()
        {
        }
        
        public timbradoCFDResponse(Mictlanix.CFDv32.TimbreFiscalDigital TimbreFiscalDigital)
        {
            this.TimbreFiscalDigital = TimbreFiscalDigital;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimbradoCFDIChannel : Mictlanix.DiverzaClient.TimbradoCFDI, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimbradoCFDIClient : System.ServiceModel.ClientBase<Mictlanix.DiverzaClient.TimbradoCFDI>, Mictlanix.DiverzaClient.TimbradoCFDI
    {
        
        public TimbradoCFDIClient()
        {
        }
        
        public TimbradoCFDIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TimbradoCFDIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TimbradoCFDIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TimbradoCFDIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mictlanix.DiverzaClient.timbradoCFDResponse Mictlanix.DiverzaClient.TimbradoCFDI.timbradoCFD(Mictlanix.DiverzaClient.timbradoCFDRequest request)
        {
            return base.Channel.timbradoCFD(request);
        }
        
        public Mictlanix.CFDv32.TimbreFiscalDigital timbradoCFD(Mictlanix.DiverzaClient.RequestTimbradoCFDType RequestTimbradoCFD)
        {
            Mictlanix.DiverzaClient.timbradoCFDRequest inValue = new Mictlanix.DiverzaClient.timbradoCFDRequest();
            inValue.RequestTimbradoCFD = RequestTimbradoCFD;
            Mictlanix.DiverzaClient.timbradoCFDResponse retVal = ((Mictlanix.DiverzaClient.TimbradoCFDI)(this)).timbradoCFD(inValue);
            return retVal.TimbreFiscalDigital;
        }
    }
}
